### ISSUE TITLE
Нет работы с кроликом

### ISSUE THREAD

**Issue by MariaNosareva** [MaksimTimokhin/backend-hw#1]
https://github.com/MaksimTimokhin/backend-hw/blob/67d7febdc985e5168cbd8a9aa7cacc7e730eb67c/postman.py#L9

Отправка писем происходит сразу при регистрации в обход кролика. В postman.py никакой логики

**Comment by MaksimTimokhin** [comment]
Я сделал, просто вы рано посмотрели
